---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: portfolio/index.md
  label: Homepage
  templates:
  - settings
- type: directory
  path: portfolio/news
  label: news
  create: documents
  match: "**/[!index]*"
  exclude: index
  templates:
  - news
- type: directory
  path: portfolio/events
  label: Events
  create: all
  match: "**/[!index]*"
  templates:
  - news
- type: heading
  label: Data
- type: document
  path: portfolio/config.json
  label: Site Config
upload_dir: mamc/media
public_path: media
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: portfolio/.vuepress/dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run site:develop
