---
new_page_extension: md
auto_deploy: true
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: site/index.md
  label: Homepage
  templates:
  - settings
- type: document
  path: site/about-us/index.md
  label: About us
- type: directory
  path: site/news
  label: News
  create: documents
  match: "**/[!index]*"
  exclude: index
  templates:
  - news
- type: directory
  path: site/events
  label: Events
  create: all
  match: "**/[!index]*"
  templates:
  - event
- type: heading
  label: Data
- type: document
  path: site/config.json
  label: Site Config
upload_dir: mamc/media
public_path: media
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: site/.vuepress/dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run site:develop
